### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Stexinator** [Siryphas/Witcher-Compendium#1]
Hey,

can you write a manual how to install it?

Thanks

**Comment by Godsassassin007** [comment]
> Hey,
> 
> can you write a manual how to install it?
> 
> Thanks

Not the author but it's easy to install. On my phone right now so can't make a detailed instructions (can tonight).

Basically it's the same as installing custom game systems. Just paste this into the install module url box

https://github.com/Siryphas/Witcher-Compendium/blob/main/wtrpg-compendium/module.json

And it should import it all. Although I know lots of people have had trouble with it working (which is why I suggested including it directly into your fork of the system).

 In this case you can install it manually by downloading the zip and putting it into the FoundryVTT/Data/modules folder.
